baseURL = "https://www.example.com/"
languageCode = "en-us"
title = "SolidExperts LDA"
themesDir = "../.."
theme = "hugo-hero-theme"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"
    
[params]
  google_analytics_id=""

  [params.logo] 
    mobile = "images/SE3.png"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/SE4.png"
    desktop_height = "29px"
    desktop_width = "217px"
    alt = "SolidExperts IT"

  [params.homepage_meta_tags]
    meta_description = "Our company has the best specialists in the .NET platform, they are good technicians and, above all, people with humility to deal with other people."
    meta_og_title = "SolidExperts LDA"
    meta_og_type = "website"
    meta_og_url = "https://solidexpertslda.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "Our company has the best specialists in the .NET platform, they are good technicians and, above all, people with humility to deal with other people."
    meta_twitter_card = "summary"
    meta_twitter_site = "@zerostaticio"
    meta_twitter_creator = "@zerostaticio"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
